name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  tag:
    name: Deploy plugin for new Tag
    runs-on: ubuntu-latest
    steps:
   
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Use desired version of php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: wp-cli
      - name: Install and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
      - name: Composer install and build
        run: |
          composer install --no-dev --optimize-autoloader
      - name: Generate zip
        uses: 10up/action-wordpress-plugin-build-zip@stable
        with:
          retention-days: 5
        env:
         SLUG: wedevs-project-manager # optional, remove if GitHub repo name matches SVN slug, including capitalization
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: false
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wedevs-project-manager
